"""1930 provinces for Para Bellum (AD-023, AD-027).

Loads ``data/boundaries/provinces_1930.geojson`` (polygons) + the paired
``provinces_1930_metadata.json`` (capital + sub-capitals per province), both
generated by ``tools/build_provinces_1930.py`` from Natural Earth admin-1
(public domain, 1930 stopgap per AD-018/AD-027).

Two responsibilities, mirroring geo/boundaries.py:
  * ``assign_province(lon, lat, pset)`` — per-hex point-in-polygon (a TILE-LOCAL
    lookup against a GLOBAL input, like country_at_start; same coastal snap).
  * ``assign_admin_tiers(result, grid, pset, settlements_gdf)`` — a GLOBAL
    reconcile pass (needs the whole grid + all settlement nodes) that designates
    each hex's admin_tier (capital / sub_capital / urban / rural / none) by
    matching province capital + sub-capital names to OSM settlement nodes.
"""

from __future__ import annotations

import json
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path

import geopandas as gpd
from rich.console import Console
from shapely.geometry import Point
from shapely.prepared import prep

from wargame_cartographer.terrain.types import WATER_BIOMES

console = Console()

_REPO_ROOT = Path(__file__).resolve().parents[3]
PROVINCES_FILE = _REPO_ROOT / "data" / "boundaries" / "provinces_1930.geojson"
METADATA_FILE = _REPO_ROOT / "data" / "boundaries" / "provinces_1930_metadata.json"

# Coastal snap tolerance (degrees) — same rationale as boundaries.COASTAL_SNAP_DEG
# (AD-010): coarse NE coastlines leave real coastal land just outside every
# polygon; snap such hex centers to the nearest province.
COASTAL_SNAP_DEG = 0.2


@dataclass
class ProvinceSet:
    """Province polygons + capital/sub-capital metadata."""
    gdf: gpd.GeoDataFrame              # geometry, province_id, name, country
    metadata: dict                    # parsed provinces_1930_metadata.json
    _prepared: list = field(default=None, repr=False)

    @property
    def prepared(self) -> list:
        if self._prepared is None or len(self._prepared) != len(self.gdf):
            self._prepared = [prep(g) for g in self.gdf.geometry.values]
        return self._prepared


def load_provinces(
    geojson_path: Path | None = None, metadata_path: Path | None = None
) -> ProvinceSet:
    """Load the repo-committed 1930 provinces + metadata."""
    gpath = Path(geojson_path) if geojson_path else PROVINCES_FILE
    mpath = Path(metadata_path) if metadata_path else METADATA_FILE
    if not gpath.exists():
        raise FileNotFoundError(
            f"Provinces file not found: {gpath} (run tools/build_provinces_1930.py, AD-027)"
        )
    gdf = gpd.read_file(gpath)[["geometry", "province_id", "name", "country"]]
    metadata = {"provinces": []}
    if mpath.exists():
        with open(mpath, encoding="utf-8") as f:
            metadata = json.load(f)
    return ProvinceSet(gdf=gdf, metadata=metadata)


def assign_province(lon: float, lat: float, pset: ProvinceSet) -> str | None:
    """Return the province_id containing point (lon, lat), or None.

    sindex shortlist + prepared covers(), then a COASTAL_SNAP_DEG nearest-province
    fallback (coarse-coastline guard, AD-010). None when no province within reach
    (open sea, or land outside the authored 5-country coverage).
    """
    if pset is None or pset.gdf.empty:
        return None
    pt = Point(lon, lat)
    gdf = pset.gdf
    prepared = pset.prepared
    ids = gdf["province_id"].values

    for idx in gdf.sindex.query(pt):
        if prepared[idx].covers(pt):
            return str(ids[idx])

    best_id = None
    best_dist = COASTAL_SNAP_DEG
    geoms = gdf.geometry.values
    for idx in gdf.sindex.query(pt.buffer(COASTAL_SNAP_DEG)):
        d = geoms[idx].distance(pt)
        if d < best_dist:
            best_dist = d
            best_id = str(ids[idx])
    return best_id


# ---------------------------------------------------------------------------
# admin_tier global reconcile pass
# ---------------------------------------------------------------------------

def _norm(s: str) -> str:
    """lowercase, accent-strip, punctuation→space — cross-language name matching.

    Punctuation is replaced by a SPACE, not deleted, so hyphen/apostrophe names
    keep their word boundaries ("Charleville-Mézières" → "charleville mezieres";
    "'s-Gravenhage" → "s gravenhage"). Otherwise they collapse into one opaque
    token and the whole-token rules in _match_score can never fire. ``ß`` is
    folded to ``ss`` (NFKD leaves it intact) so "Gießen" == "Giessen".
    """
    s = (s or "").replace("ß", "ss").replace("ẞ", "ss")
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = "".join(c if (c.isalnum() or c == " ") else " " for c in s.lower())
    return " ".join(s.split())


def _match_score(meta_name: str, node_norm: str) -> int:
    """Score a metadata city name against a (normalised) OSM node name.

    WHOLE-TOKEN matching — never raw substring containment, which would match
    "As" (a Limburg town) to "H-as-selt". Higher score = better match; 0 = no
    match. best_match prefers score, then population, so an exact pop-0 capital
    node beats a higher-pop false fuzzy hit.
      100  exact normalised equality
       70  one name is a whole token of the other ("Frankfurt" ~ "Frankfurt am
            Main"; "Brussel" ~ "Bruxelles - Brussel")
       50  a shared significant (>=4-char) whole token
    """
    a = _norm(meta_name)
    if not a or not node_norm:
        return 0
    if a == node_norm:
        return 100
    ta, tb = set(a.split()), set(node_norm.split())
    if a in tb or node_norm in ta:
        return 70
    if {t for t in (ta & tb) if len(t) >= 4}:
        return 50
    return 0


def _designate(data: dict, tier: str, node_name: str, pop: int) -> None:
    """Mark a hex as a capital/sub_capital, ensuring it reads as a settled place."""
    data["admin_tier"] = tier
    if data.get("settlement_type", "none") == "none":
        # A capital below the hex-scale tagging floor still IS a settlement.
        data["settlement_type"] = "city" if pop >= 50_000 else "town"
        data["settlement_name"] = node_name
        data["population_class"] = 3 if pop >= 50_000 else 2
        if data.get("anthrome", "none") == "none":
            data["anthrome"] = "residential"
    elif not data.get("settlement_name"):
        data["settlement_name"] = node_name


def assign_admin_tiers(
    result: dict, grid, pset: ProvinceSet, settlements_gdf
) -> None:
    """Global pass: set admin_tier on every hex (AD-023, B4).

    Base tier from province + settlement; then designate capital/sub_capital
    hexes by matching the metadata names to OSM settlement nodes that fall
    inside the province. Mutates ``result`` in place. Safe to call with pset
    None (leaves admin_tier unset → exporter falls back to the v1.0.3 default).
    """
    if pset is None:
        return

    # --- base tier for every hex ---
    for d in result.values():
        is_water = d.get("biome") in WATER_BIOMES
        country = d.get("country_at_start", "")
        prov = d.get("province_at_start", "")
        if is_water or not country or not prov:
            d["admin_tier"] = "none"
        else:
            d["admin_tier"] = "urban" if d.get("settlement_type", "none") != "none" else "rural"

    if settlements_gdf is None or settlements_gdf.empty:
        return

    # --- group OSM settlement nodes by the province of their hex ---
    from wargame_cartographer.hex.sampler import _point_to_hex
    xs, ys = grid._to_proj.transform(
        settlements_gdf.geometry.x.values, settlements_gdf.geometry.y.values
    )
    pops = settlements_gdf["population"].values if "population" in settlements_gdf.columns \
        else [0] * len(settlements_gdf)
    names = settlements_gdf["name"].values
    prov_nodes: dict[str, list[tuple]] = {}
    for x, y, nm, pop in zip(xs, ys, names, pops):
        qr = _point_to_hex(grid, x, y)
        if qr is None or qr not in result:
            continue
        pid = result[qr].get("province_at_start", "")
        if not pid:
            continue
        popi = int(pop) if pop == pop else 0  # NaN guard
        prov_nodes.setdefault(pid, []).append((qr, popi, _norm(str(nm))))

    # --- designate capital + sub_capitals per province ---
    stats = {"capital": 0, "sub_capital": 0, "no_capital": []}
    for prov in pset.metadata.get("provinces", []):
        pid = prov["province_id"]
        cands = prov_nodes.get(pid, [])
        claimed: set = set()

        def best_match(city_name: str):
            # Prefer match quality, then population (so an exact pop-0 node beats
            # a higher-pop weaker match).
            hits = [(_match_score(city_name, nn), pop, qr)
                    for (qr, pop, nn) in cands if qr not in claimed]
            hits = [h for h in hits if h[0] > 0]
            return max(hits)[2] if hits else None

        cap_name = (prov.get("capital") or {}).get("city_name", "")
        cap_qr = best_match(cap_name) if cap_name else None
        if cap_qr is not None:
            pop = next((p for (q, p, n) in cands if q == cap_qr), 0)
            _designate(result[cap_qr], "capital", cap_name, pop)
            claimed.add(cap_qr)
            stats["capital"] += 1
        else:
            stats["no_capital"].append(pid)

        for sub in prov.get("sub_capitals", []):
            sname = sub.get("city_name", "")
            sqr = best_match(sname) if sname else None
            if sqr is not None and result[sqr].get("admin_tier") != "capital":
                pop = next((p for (q, p, n) in cands if q == sqr), 0)
                _designate(result[sqr], "sub_capital", sname, pop)
                claimed.add(sqr)
                stats["sub_capital"] += 1

    console.print(
        f"  [global] admin tiers: {stats['capital']} capitals, "
        f"{stats['sub_capital']} sub-capitals"
        + (f"; {len(stats['no_capital'])} provinces with no in-grid capital"
           if stats["no_capital"] else ""),
        style="dim",
    )
